### PR TITLE
Meta-tests

### LINKED ISSUE #13: meta-tests
Check that all error messages (TRIO<XXX>) are mentioned in all four of `README.md` `CHANGELOG.md` `flake8_trio.py` and `tests/test_flake8_trio.py`.

Check that the line numbers of the set of lines in `tests/trio*.py` with an `# error` comment are the same as the line numbers in lines matching `make_error[...] <lineno> [...]` in `tests/test_flake8_trio.py`. As lines are moved around and specs change I get increasingly worried that these don't match.

### PR DESCRIPTION
**Pull request by jakkdl**
Fixes #13 

Also found what I think is a bug in TRIO100, and added TRIO106 to `README.md`

### CODE REVIEW

**Review by Zac-HD — APPROVED** [review]
Nice ✅ 

Quick style note, if you're comfortable with pytest-style test functions I'm just as happy to use those as unittest classes.

**Comment by jakkdl** [comment]
I haven't used either extensively enough to have too much of an opinion - but I needed access to a `msg` parameter to give more info and the first place I looked that had it was unittest.

Even better would be to have multiple different tests generated for each file, instead of it quitting on the first file/test pair that fails, but didn't bother spending time on figuring out how to do that.

**Comment by Zac-HD** [comment]
`assert condition, "message"` is the pytest idiom fyi 🙂

Agree that it's not worth extending further though!

**Comment by jakkdl** [comment]
Thank you, good to know!

**Pull request merged**
